apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service-deployment
  namespace: vidyalayaone-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
      - name: attendance-service
        image: asia-south2-docker.pkg.dev/vidyalayaone/vidyalayaone-repo/attendance-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        envFrom:
        - configMapRef:
            name: attendance-service-config
        - secretRef:
            name: attendance-service-secret
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
