apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-frontend-deployment
  namespace: vidyalayaone-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: platform-frontend
    spec:
      containers:
      - name: platform-frontend
        image: asia-south2-docker.pkg.dev/vidyalayaone/vidyalayaone-repo/platform-frontend:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
