name: School-Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'apps/school-frontend/**'
      - 'packages/**'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'tsconfig.base.json'
      - 'k8s-manifests/deployments/school-frontend-deployment.yaml'
      - 'k8s-manifests/services/school-frontend-service.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Setup gcloud (optional, for kubectl & CLI)
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: vidyalayaone

      # 4. Configure Docker for GCP Artifact Registry
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-south2-docker.pkg.dev

      # 5. Build Docker image
      - name: Build Docker Image
        run: docker build -f apps/school-frontend/Dockerfile.prod -t school-frontend:prod .

      # 6. Tag the image for Artifact Registry
      - name: Tag Docker Image
        run: docker tag school-frontend:prod asia-south2-docker.pkg.dev/vidyalayaone/vidyalayaone-repo/school-frontend:latest

      # 7. Push image to Artifact Registry
      - name: Push Docker Image
        run: docker push asia-south2-docker.pkg.dev/vidyalayaone/vidyalayaone-repo/school-frontend:latest

      - name: Install kubectl
        run: |
          gcloud components install kubectl gke-gcloud-auth-plugin -q

      - name: Get credentials for GKE cluster
        run: |
          gcloud container clusters get-credentials vidyalayaone-cluster --zone asia-south2-a --project vidyalayaone

      - name: Rollout Deployment
        run: |
          kubectl rollout restart deployment/school-frontend-deployment -n vidyalayaone-prod
          kubectl rollout status deployment/school-frontend-deployment -n vidyalayaone-prod
